<?php

/**
 * Implements of hook_views_api().
 */
function views_term_path_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_term_path') . '/views',
  );
}

/**
 * Implements of hook_autoload_info().
 */
function views_term_path_autoload_info() {
  return array(
    'views_term_path_handler_field_path' => 'includes/views_term_path_handler_field_path.inc',
  );
}
