<?php

/**
 * Implements of hook_views_api().
 */
function views_term_path_views_api() {
  return array('api' => 3);
}

/**
 * Implements of hook_autoload_info().
 */
function views_term_path_autoload_info() {
  return array(
    'views_term_path_handler_field_path' => 'includes/views_term_path_handler_field_path.inc',
  );
}

/**
  * Load include file.
  */
module_load_include('inc','views_term_path','includes/views_term_path.views');

